import { constants } from "node:fs";
import { access, chmod, lstat, mkdir, realpath } from "node:fs/promises";
import { delimiter, isAbsolute, join } from "node:path";
import { createLogger } from "../../observability/logger.js";
import { ensurePrivateDirectory, readSecureFile, writeDurableFile } from "../../storage/durable-file.js";
import { type ProviderCliAccountLayout, providerCliLauncherPath } from "./account-layout.js";
import type { ProviderCliCatalogEntry } from "./catalog.js";
import type { ProviderCliSelection } from "./selection-store.js";
import type { ProviderCliProvider } from "./types.js";

/**
 * Account-global launchers and public shims.
 *
 * The internal launcher (`provider-cli/bin/<command>`) is the authoritative OpenTag
 * Runtime entrypoint: a tiny POSIX shell script that execs the exact selected target,
 * forwarding argv, stdin, stdout, stderr, signals, and exit status without interpreting
 * provider operations. Managed targets additionally get update checks disabled; an
 * external target keeps its operator-owned behavior.
 *
 * The public shim (`<account-home>/.local/bin/<command>`) only forwards to the internal
 * launcher so a human shell can use the native command name. An unmanaged file already
 * occupying that name is never overwritten.
 */

const LAUNCHER_MARKER = "# opentag-provider-cli-launcher: v1";
const SHIM_MARKER = "# opentag-provider-cli-shim: v1";
const logger = createLogger("runtime-provider-cli-launcher");

export type ProviderCliLauncherStatus = "valid" | "missing" | "invalid" | "mismatch";

function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

/** Deterministic launcher content for a selection; compared byte-for-byte on inspect. */
export function renderProviderCliLauncher(entry: ProviderCliCatalogEntry, selection: ProviderCliSelection): string {
  const target = selection.kind === "managed" ? selection.targetPath : selection.executablePath;
  const lines = [
    "#!/bin/sh",
    `${LAUNCHER_MARKER} provider=${entry.provider} kind=${selection.kind}`,
    "# OpenTag-managed launcher. Regenerated by `opentag provider-cli ensure`; do not edit.",
  ];
  if (selection.kind === "managed") {
    for (const [name, value] of Object.entries(entry.managedEnvironment)) {
      lines.push(`export ${name}=${shellSingleQuote(value)}`);
    }
  }
  const args =
    selection.kind === "managed" && entry.managedArguments.length > 0
      ? ` ${entry.managedArguments.map(shellSingleQuote).join(" ")}`
      : "";
  lines.push(`exec ${shellSingleQuote(target)}${args} "$@"`);
  return `${lines.join("\n")}\n`;
}

/** Deterministic public shim content. */
export function renderProviderCliShim(provider: ProviderCliProvider, launcherPath: string): string {
  return ["#!/bin/sh", `${SHIM_MARKER} provider=${provider}`, `exec ${shellSingleQuote(launcherPath)} "$@"`, ""].join(
    "\n",
  );
}

export function isProviderCliLauncherContent(content: string, provider: ProviderCliProvider): boolean {
  return content.startsWith(`#!/bin/sh\n${LAUNCHER_MARKER} provider=${provider} `);
}

/** Write or repair the internal launcher to match the selection. */
export async function reconcileProviderCliLauncher(
  layout: ProviderCliAccountLayout,
  entry: ProviderCliCatalogEntry,
  selection: ProviderCliSelection,
): Promise<{ path: string; changed: boolean }> {
  const launcherPath = providerCliLauncherPath(layout, entry.command);
  await ensurePrivateDirectory(layout.root, layout.bin);
  const expected = renderProviderCliLauncher(entry, selection);
  const current = await readSecureFile(launcherPath).catch((error: unknown) => {
    logger.debug({ code: "launcher_read_failed", error: String(error) }, "Provider CLI launcher read failed");
    return undefined;
  });
  if (current === expected) {
    await chmod(launcherPath, 0o755);
    return { path: launcherPath, changed: false };
  }
  await writeDurableFile(launcherPath, expected, 0o755);
  await chmod(launcherPath, 0o755);
  return { path: launcherPath, changed: true };
}

export async function inspectProviderCliLauncher(
  layout: ProviderCliAccountLayout,
  entry: ProviderCliCatalogEntry,
  selection: ProviderCliSelection | undefined,
): Promise<{ status: ProviderCliLauncherStatus; path: string }> {
  const launcherPath = providerCliLauncherPath(layout, entry.command);
  const content = await readSecureFile(launcherPath).catch((error: unknown) => {
    logger.debug(
      { code: "launcher_inspection_read_failed", error: String(error) },
      "Provider CLI launcher inspection read failed",
    );
    return undefined;
  });
  if (content === undefined) return { status: "missing", path: launcherPath };
  if (!isProviderCliLauncherContent(content, entry.provider)) return { status: "invalid", path: launcherPath };
  if (selection && content !== renderProviderCliLauncher(entry, selection)) {
    return { status: "mismatch", path: launcherPath };
  }
  return { status: "valid", path: launcherPath };
}

export type ProviderCliShimOutcome =
  | { readonly status: "created" | "updated" | "unchanged"; readonly path: string }
  | { readonly status: "occupied"; readonly path: string };

/**
 * Create or refresh the OpenTag-owned public shim. An unmanaged file occupying the
 * public command name is left untouched and reported as `occupied`.
 */
export async function reconcileProviderCliShim(
  layout: ProviderCliAccountLayout,
  entry: ProviderCliCatalogEntry,
): Promise<ProviderCliShimOutcome> {
  const shimPath = join(layout.publicBinDir, entry.command);
  const launcherPath = providerCliLauncherPath(layout, entry.command);
  const expected = renderProviderCliShim(entry.provider, launcherPath);
  const current = await readSecureFile(shimPath).catch((error: unknown) => {
    logger.debug({ code: "shim_read_failed", error: String(error) }, "Provider CLI shim read failed");
    return undefined;
  });
  if (current === expected) {
    await chmod(shimPath, 0o755);
    return { status: "unchanged", path: shimPath };
  }
  if (current !== undefined && !current.startsWith(`#!/bin/sh\n${SHIM_MARKER} `)) {
    return { status: "occupied", path: shimPath };
  }
  // The public bin directory is shared, conventional, and world-readable by design;
  // writeDurableFile still refuses symlinked parents when writing the shim itself.
  await mkdir(layout.publicBinDir, { recursive: true, mode: 0o755 });
  await writeDurableFile(shimPath, expected, 0o755);
  await chmod(shimPath, 0o755);
  return { status: current === undefined ? "created" : "updated", path: shimPath };
}

export interface ProviderCliGlobalCommandStatus {
  readonly active: boolean;
  /** The OpenTag public shim path when it exists and is ours. */
  readonly path?: string;
  /** What the invoking shell's PATH resolves the bare command to, if anything. */
  readonly resolvedPath?: string;
  /** True when a different command shadows the OpenTag shim on PATH. */
  readonly shadowed: boolean;
}

/**
 * Resolve the bare command name against the invoking environment's PATH the way a
 * shell would (first executable match wins) and compare it with the OpenTag shim.
 * Read-only; this is detection-scope information, never daemon readiness.
 */
export async function inspectGlobalCommand(
  layout: ProviderCliAccountLayout,
  command: string,
  env: NodeJS.ProcessEnv,
): Promise<ProviderCliGlobalCommandStatus> {
  const shimPath = join(layout.publicBinDir, command);
  const shimContent = await readSecureFile(shimPath).catch((error: unknown) => {
    logger.debug({ code: "global_shim_read_failed", error: String(error) }, "Provider CLI global shim read failed");
    return undefined;
  });
  const ours = shimContent?.startsWith(`#!/bin/sh\n${SHIM_MARKER} `) === true;
  const launcherPath = providerCliLauncherPath(layout, command);

  let resolvedPath: string | undefined;
  for (const entry of (env.PATH ?? "").split(delimiter)) {
    if (entry.length === 0 || !isAbsolute(entry)) continue;
    const candidate = join(entry, command);
    try {
      await access(candidate, constants.X_OK);
      const status = await lstat(candidate);
      if (!status.isFile() && !status.isSymbolicLink()) continue;
      resolvedPath = await realpath(candidate);
      break;
    } catch (error) {
      logger.debug(
        { code: "global_command_resolution_failed", error: String(error) },
        "Provider CLI global command resolution failed",
      );
    }
  }

  const shimCanonical = ours
    ? await realpath(shimPath).catch((error: unknown) => {
        logger.debug(
          { code: "shim_realpath_failed", error: String(error) },
          "Provider CLI shim canonicalization failed",
        );
        return shimPath;
      })
    : undefined;
  const launcherCanonical = await realpath(launcherPath).catch((error: unknown) => {
    logger.debug(
      { code: "launcher_realpath_failed", error: String(error) },
      "Provider CLI launcher canonicalization failed",
    );
    return undefined;
  });
  const active = resolvedPath !== undefined && (resolvedPath === shimCanonical || resolvedPath === launcherCanonical);
  const shadowed = resolvedPath !== undefined && !active;
  return {
    active,
    ...(ours ? { path: shimPath } : {}),
    ...(resolvedPath ? { resolvedPath } : {}),
    shadowed,
  };
}
