/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/_resources'
import { Route as InternalOnboardingV2RouteImport } from './routes/internal.onboarding-v2'
import { Route as AuthenticatedWorkspaceShellRouteImport } from './routes/_authenticated/_resources/_shell'
import { Route as AuthenticatedWorkspaceOnboardingRouteImport } from './routes/_authenticated/_resources/onboarding'
import { Route as AuthenticatedInternalIndexRouteImport } from './routes/_authenticated/internal.index'
import { Route as AuthenticatedWorkspaceShellIndexRouteImport } from './routes/_authenticated/_resources/_shell/index'
import { Route as AuthenticatedWorkspaceShellAccountRouteImport } from './routes/_authenticated/_resources/_shell/account'
import { Route as AuthenticatedWorkspaceShellIntegrationsRouteImport } from './routes/_authenticated/_resources/_shell/integrations'
import { Route as AuthenticatedWorkspaceShellResourcesRouteImport } from './routes/_authenticated/_resources/_shell/resources'
import { Route as AuthenticatedWorkspaceShellSkillsRouteImport } from './routes/_authenticated/_resources/_shell/skills'
import { Route as AuthenticatedWorkspaceShellUsageRouteImport } from './routes/_authenticated/_resources/_shell/usage'
import { Route as AuthenticatedWorkspaceShellAgentsIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.index'
import { Route as AuthenticatedWorkspaceShellAgentsComputersRouteImport } from './routes/_authenticated/_resources/_shell/agents.computers'
import { Route as AuthenticatedWorkspaceShellAgentsNewRouteImport } from './routes/_authenticated/_resources/_shell/agents.new'
import { Route as AuthenticatedWorkspaceShellTasksIndexRouteImport } from './routes/_authenticated/_resources/_shell/tasks.index'
import { Route as AuthenticatedWorkspaceShellTasksTaskIdRouteImport } from './routes/_authenticated/_resources/_shell/tasks.$taskId'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.index'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.$legacySection'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.integrations'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdSkillsRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.skills'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdUsageRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.usage'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.settings.index'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.settings.$section'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.tasks.index'
import { Route as AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.tasks.$taskId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InternalOnboardingV2Route = InternalOnboardingV2RouteImport.update({
  id: '/internal/onboarding-v2',
  path: '/internal/onboarding-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceShellRoute =
  AuthenticatedWorkspaceShellRouteImport.update({
    id: '/_shell',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceOnboardingRoute =
  AuthenticatedWorkspaceOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedInternalIndexRoute =
  AuthenticatedInternalIndexRouteImport.update({
    id: '/internal/',
    path: '/internal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceShellIndexRoute =
  AuthenticatedWorkspaceShellIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAccountRoute =
  AuthenticatedWorkspaceShellAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellIntegrationsRoute =
  AuthenticatedWorkspaceShellIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellResourcesRoute =
  AuthenticatedWorkspaceShellResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellSkillsRoute =
  AuthenticatedWorkspaceShellSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellUsageRoute =
  AuthenticatedWorkspaceShellUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsIndexRoute =
  AuthenticatedWorkspaceShellAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsComputersRoute =
  AuthenticatedWorkspaceShellAgentsComputersRouteImport.update({
    id: '/agents/computers',
    path: '/agents/computers',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsNewRoute =
  AuthenticatedWorkspaceShellAgentsNewRouteImport.update({
    id: '/agents/new',
    path: '/agents/new',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellTasksIndexRoute =
  AuthenticatedWorkspaceShellTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellTasksTaskIdRoute =
  AuthenticatedWorkspaceShellTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRouteImport.update({
    id: '/agents/$agentId/$legacySection',
    path: '/agents/$agentId/$legacySection',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRouteImport.update({
    id: '/agents/$agentId/integrations',
    path: '/agents/$agentId/integrations',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdSkillsRouteImport.update({
    id: '/agents/$agentId/skills',
    path: '/agents/$agentId/skills',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdUsageRouteImport.update({
    id: '/agents/$agentId/usage',
    path: '/agents/$agentId/usage',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRouteImport.update({
    id: '/agents/$agentId/settings/',
    path: '/agents/$agentId/settings/',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRouteImport.update({
    id: '/agents/$agentId/settings/$section',
    path: '/agents/$agentId/settings/$section',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRouteImport.update({
    id: '/agents/$agentId/tasks/',
    path: '/agents/$agentId/tasks/',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)
const AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute =
  AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRouteImport.update({
    id: '/agents/$agentId/tasks/$taskId',
    path: '/agents/$agentId/tasks/$taskId',
    getParentRoute: () => AuthenticatedWorkspaceShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedWorkspaceShellIndexRoute
  '/login': typeof LoginRoute
  '/internal/onboarding-v2': typeof InternalOnboardingV2Route
  '/onboarding': typeof AuthenticatedWorkspaceOnboardingRoute
  '/internal/': typeof AuthenticatedInternalIndexRoute
  '/account': typeof AuthenticatedWorkspaceShellAccountRoute
  '/integrations': typeof AuthenticatedWorkspaceShellIntegrationsRoute
  '/resources': typeof AuthenticatedWorkspaceShellResourcesRoute
  '/skills': typeof AuthenticatedWorkspaceShellSkillsRoute
  '/usage': typeof AuthenticatedWorkspaceShellUsageRoute
  '/agents/computers': typeof AuthenticatedWorkspaceShellAgentsComputersRoute
  '/agents/new': typeof AuthenticatedWorkspaceShellAgentsNewRoute
  '/tasks/$taskId': typeof AuthenticatedWorkspaceShellTasksTaskIdRoute
  '/agents/': typeof AuthenticatedWorkspaceShellAgentsIndexRoute
  '/tasks/': typeof AuthenticatedWorkspaceShellTasksIndexRoute
  '/agents/$agentId/$legacySection': typeof AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute
  '/agents/$agentId/integrations': typeof AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute
  '/agents/$agentId/skills': typeof AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute
  '/agents/$agentId/usage': typeof AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute
  '/agents/$agentId/': typeof AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute
  '/agents/$agentId/settings/$section': typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute
  '/agents/$agentId/tasks/$taskId': typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute
  '/agents/$agentId/settings/': typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute
  '/agents/$agentId/tasks/': typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedWorkspaceShellIndexRoute
  '/login': typeof LoginRoute
  '/internal/onboarding-v2': typeof InternalOnboardingV2Route
  '/onboarding': typeof AuthenticatedWorkspaceOnboardingRoute
  '/internal': typeof AuthenticatedInternalIndexRoute
  '/account': typeof AuthenticatedWorkspaceShellAccountRoute
  '/integrations': typeof AuthenticatedWorkspaceShellIntegrationsRoute
  '/resources': typeof AuthenticatedWorkspaceShellResourcesRoute
  '/skills': typeof AuthenticatedWorkspaceShellSkillsRoute
  '/usage': typeof AuthenticatedWorkspaceShellUsageRoute
  '/agents/computers': typeof AuthenticatedWorkspaceShellAgentsComputersRoute
  '/agents/new': typeof AuthenticatedWorkspaceShellAgentsNewRoute
  '/tasks/$taskId': typeof AuthenticatedWorkspaceShellTasksTaskIdRoute
  '/agents': typeof AuthenticatedWorkspaceShellAgentsIndexRoute
  '/tasks': typeof AuthenticatedWorkspaceShellTasksIndexRoute
  '/agents/$agentId/$legacySection': typeof AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute
  '/agents/$agentId/integrations': typeof AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute
  '/agents/$agentId/skills': typeof AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute
  '/agents/$agentId/usage': typeof AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute
  '/agents/$agentId': typeof AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute
  '/agents/$agentId/settings/$section': typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute
  '/agents/$agentId/tasks/$taskId': typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute
  '/agents/$agentId/settings': typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute
  '/agents/$agentId/tasks': typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_resources': typeof AuthenticatedWorkspaceRouteWithChildren
  '/internal/onboarding-v2': typeof InternalOnboardingV2Route
  '/_authenticated/_resources/_shell': typeof AuthenticatedWorkspaceShellRouteWithChildren
  '/_authenticated/_resources/onboarding': typeof AuthenticatedWorkspaceOnboardingRoute
  '/_authenticated/internal/': typeof AuthenticatedInternalIndexRoute
  '/_authenticated/_resources/_shell/account': typeof AuthenticatedWorkspaceShellAccountRoute
  '/_authenticated/_resources/_shell/integrations': typeof AuthenticatedWorkspaceShellIntegrationsRoute
  '/_authenticated/_resources/_shell/resources': typeof AuthenticatedWorkspaceShellResourcesRoute
  '/_authenticated/_resources/_shell/skills': typeof AuthenticatedWorkspaceShellSkillsRoute
  '/_authenticated/_resources/_shell/usage': typeof AuthenticatedWorkspaceShellUsageRoute
  '/_authenticated/_resources/_shell/': typeof AuthenticatedWorkspaceShellIndexRoute
  '/_authenticated/_resources/_shell/agents/computers': typeof AuthenticatedWorkspaceShellAgentsComputersRoute
  '/_authenticated/_resources/_shell/agents/new': typeof AuthenticatedWorkspaceShellAgentsNewRoute
  '/_authenticated/_resources/_shell/tasks/$taskId': typeof AuthenticatedWorkspaceShellTasksTaskIdRoute
  '/_authenticated/_resources/_shell/agents/': typeof AuthenticatedWorkspaceShellAgentsIndexRoute
  '/_authenticated/_resources/_shell/tasks/': typeof AuthenticatedWorkspaceShellTasksIndexRoute
  '/_authenticated/_resources/_shell/agents/$agentId/$legacySection': typeof AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute
  '/_authenticated/_resources/_shell/agents/$agentId/integrations': typeof AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute
  '/_authenticated/_resources/_shell/agents/$agentId/skills': typeof AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute
  '/_authenticated/_resources/_shell/agents/$agentId/usage': typeof AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute
  '/_authenticated/_resources/_shell/agents/$agentId/': typeof AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute
  '/_authenticated/_resources/_shell/agents/$agentId/settings/$section': typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute
  '/_authenticated/_resources/_shell/agents/$agentId/tasks/$taskId': typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute
  '/_authenticated/_resources/_shell/agents/$agentId/settings/': typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute
  '/_authenticated/_resources/_shell/agents/$agentId/tasks/': typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/internal/onboarding-v2'
    | '/onboarding'
    | '/internal/'
    | '/account'
    | '/integrations'
    | '/resources'
    | '/skills'
    | '/usage'
    | '/agents/computers'
    | '/agents/new'
    | '/tasks/$taskId'
    | '/agents/'
    | '/tasks/'
    | '/agents/$agentId/$legacySection'
    | '/agents/$agentId/integrations'
    | '/agents/$agentId/skills'
    | '/agents/$agentId/usage'
    | '/agents/$agentId/'
    | '/agents/$agentId/settings/$section'
    | '/agents/$agentId/tasks/$taskId'
    | '/agents/$agentId/settings/'
    | '/agents/$agentId/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/internal/onboarding-v2'
    | '/onboarding'
    | '/internal'
    | '/account'
    | '/integrations'
    | '/resources'
    | '/skills'
    | '/usage'
    | '/agents/computers'
    | '/agents/new'
    | '/tasks/$taskId'
    | '/agents'
    | '/tasks'
    | '/agents/$agentId/$legacySection'
    | '/agents/$agentId/integrations'
    | '/agents/$agentId/skills'
    | '/agents/$agentId/usage'
    | '/agents/$agentId'
    | '/agents/$agentId/settings/$section'
    | '/agents/$agentId/tasks/$taskId'
    | '/agents/$agentId/settings'
    | '/agents/$agentId/tasks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_resources'
    | '/internal/onboarding-v2'
    | '/_authenticated/_resources/_shell'
    | '/_authenticated/_resources/onboarding'
    | '/_authenticated/internal/'
    | '/_authenticated/_resources/_shell/account'
    | '/_authenticated/_resources/_shell/integrations'
    | '/_authenticated/_resources/_shell/resources'
    | '/_authenticated/_resources/_shell/skills'
    | '/_authenticated/_resources/_shell/usage'
    | '/_authenticated/_resources/_shell/'
    | '/_authenticated/_resources/_shell/agents/computers'
    | '/_authenticated/_resources/_shell/agents/new'
    | '/_authenticated/_resources/_shell/tasks/$taskId'
    | '/_authenticated/_resources/_shell/agents/'
    | '/_authenticated/_resources/_shell/tasks/'
    | '/_authenticated/_resources/_shell/agents/$agentId/$legacySection'
    | '/_authenticated/_resources/_shell/agents/$agentId/integrations'
    | '/_authenticated/_resources/_shell/agents/$agentId/skills'
    | '/_authenticated/_resources/_shell/agents/$agentId/usage'
    | '/_authenticated/_resources/_shell/agents/$agentId/'
    | '/_authenticated/_resources/_shell/agents/$agentId/settings/$section'
    | '/_authenticated/_resources/_shell/agents/$agentId/tasks/$taskId'
    | '/_authenticated/_resources/_shell/agents/$agentId/settings/'
    | '/_authenticated/_resources/_shell/agents/$agentId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  InternalOnboardingV2Route: typeof InternalOnboardingV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_resources': {
      id: '/_authenticated/_resources'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/internal/onboarding-v2': {
      id: '/internal/onboarding-v2'
      path: '/internal/onboarding-v2'
      fullPath: '/internal/onboarding-v2'
      preLoaderRoute: typeof InternalOnboardingV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_resources/_shell': {
      id: '/_authenticated/_resources/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_resources/onboarding': {
      id: '/_authenticated/_resources/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedWorkspaceOnboardingRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/internal/': {
      id: '/_authenticated/internal/'
      path: '/internal'
      fullPath: '/internal/'
      preLoaderRoute: typeof AuthenticatedInternalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_resources/_shell/': {
      id: '/_authenticated/_resources/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/account': {
      id: '/_authenticated/_resources/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAccountRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/integrations': {
      id: '/_authenticated/_resources/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellIntegrationsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/resources': {
      id: '/_authenticated/_resources/_shell/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellResourcesRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/skills': {
      id: '/_authenticated/_resources/_shell/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellSkillsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/usage': {
      id: '/_authenticated/_resources/_shell/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellUsageRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/': {
      id: '/_authenticated/_resources/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/computers': {
      id: '/_authenticated/_resources/_shell/agents/computers'
      path: '/agents/computers'
      fullPath: '/agents/computers'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsComputersRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/new': {
      id: '/_authenticated/_resources/_shell/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsNewRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/tasks/': {
      id: '/_authenticated/_resources/_shell/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellTasksIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/tasks/$taskId': {
      id: '/_authenticated/_resources/_shell/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/$legacySection': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/$legacySection'
      path: '/agents/$agentId/$legacySection'
      fullPath: '/agents/$agentId/$legacySection'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/integrations': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/integrations'
      path: '/agents/$agentId/integrations'
      fullPath: '/agents/$agentId/integrations'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/skills': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/skills'
      path: '/agents/$agentId/skills'
      fullPath: '/agents/$agentId/skills'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdSkillsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/usage': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/usage'
      path: '/agents/$agentId/usage'
      fullPath: '/agents/$agentId/usage'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdUsageRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/settings/': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/settings/'
      path: '/agents/$agentId/settings'
      fullPath: '/agents/$agentId/settings/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/settings/$section': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/settings/$section'
      path: '/agents/$agentId/settings/$section'
      fullPath: '/agents/$agentId/settings/$section'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/tasks/': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/tasks/'
      path: '/agents/$agentId/tasks'
      fullPath: '/agents/$agentId/tasks/'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/tasks/$taskId': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/tasks/$taskId'
      path: '/agents/$agentId/tasks/$taskId'
      fullPath: '/agents/$agentId/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceShellRoute
    }
  }
}

interface AuthenticatedWorkspaceShellRouteChildren {
  AuthenticatedWorkspaceShellAccountRoute: typeof AuthenticatedWorkspaceShellAccountRoute
  AuthenticatedWorkspaceShellIntegrationsRoute: typeof AuthenticatedWorkspaceShellIntegrationsRoute
  AuthenticatedWorkspaceShellResourcesRoute: typeof AuthenticatedWorkspaceShellResourcesRoute
  AuthenticatedWorkspaceShellSkillsRoute: typeof AuthenticatedWorkspaceShellSkillsRoute
  AuthenticatedWorkspaceShellUsageRoute: typeof AuthenticatedWorkspaceShellUsageRoute
  AuthenticatedWorkspaceShellIndexRoute: typeof AuthenticatedWorkspaceShellIndexRoute
  AuthenticatedWorkspaceShellAgentsComputersRoute: typeof AuthenticatedWorkspaceShellAgentsComputersRoute
  AuthenticatedWorkspaceShellAgentsNewRoute: typeof AuthenticatedWorkspaceShellAgentsNewRoute
  AuthenticatedWorkspaceShellTasksTaskIdRoute: typeof AuthenticatedWorkspaceShellTasksTaskIdRoute
  AuthenticatedWorkspaceShellAgentsIndexRoute: typeof AuthenticatedWorkspaceShellAgentsIndexRoute
  AuthenticatedWorkspaceShellTasksIndexRoute: typeof AuthenticatedWorkspaceShellTasksIndexRoute
  AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute
  AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute
  AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute
  AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute
  AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute
  AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute
  AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute
  AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute
  AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute: typeof AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute
}

const AuthenticatedWorkspaceShellRouteChildren: AuthenticatedWorkspaceShellRouteChildren =
  {
    AuthenticatedWorkspaceShellAccountRoute:
      AuthenticatedWorkspaceShellAccountRoute,
    AuthenticatedWorkspaceShellIntegrationsRoute:
      AuthenticatedWorkspaceShellIntegrationsRoute,
    AuthenticatedWorkspaceShellResourcesRoute:
      AuthenticatedWorkspaceShellResourcesRoute,
    AuthenticatedWorkspaceShellSkillsRoute:
      AuthenticatedWorkspaceShellSkillsRoute,
    AuthenticatedWorkspaceShellUsageRoute:
      AuthenticatedWorkspaceShellUsageRoute,
    AuthenticatedWorkspaceShellIndexRoute:
      AuthenticatedWorkspaceShellIndexRoute,
    AuthenticatedWorkspaceShellAgentsComputersRoute:
      AuthenticatedWorkspaceShellAgentsComputersRoute,
    AuthenticatedWorkspaceShellAgentsNewRoute:
      AuthenticatedWorkspaceShellAgentsNewRoute,
    AuthenticatedWorkspaceShellTasksTaskIdRoute:
      AuthenticatedWorkspaceShellTasksTaskIdRoute,
    AuthenticatedWorkspaceShellAgentsIndexRoute:
      AuthenticatedWorkspaceShellAgentsIndexRoute,
    AuthenticatedWorkspaceShellTasksIndexRoute:
      AuthenticatedWorkspaceShellTasksIndexRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdLegacySectionRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdIntegrationsRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdSkillsRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdUsageRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdIndexRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdSettingsSectionRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdTasksTaskIdRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdSettingsIndexRoute,
    AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute:
      AuthenticatedWorkspaceShellAgentsAgentIdTasksIndexRoute,
  }

const AuthenticatedWorkspaceShellRouteWithChildren =
  AuthenticatedWorkspaceShellRoute._addFileChildren(
    AuthenticatedWorkspaceShellRouteChildren,
  )

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceShellRoute: typeof AuthenticatedWorkspaceShellRouteWithChildren
  AuthenticatedWorkspaceOnboardingRoute: typeof AuthenticatedWorkspaceOnboardingRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceShellRoute:
      AuthenticatedWorkspaceShellRouteWithChildren,
    AuthenticatedWorkspaceOnboardingRoute:
      AuthenticatedWorkspaceOnboardingRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedInternalIndexRoute: typeof AuthenticatedInternalIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedInternalIndexRoute: AuthenticatedInternalIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  InternalOnboardingV2Route: InternalOnboardingV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
