/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/_resources'
import { Route as InternalOnboardingV2RouteImport } from './routes/internal.onboarding-v2'
import { Route as AuthenticatedResourcesShellRouteImport } from './routes/_authenticated/_resources/_shell'
import { Route as AuthenticatedResourcesOnboardingRouteImport } from './routes/_authenticated/_resources/onboarding'
import { Route as AuthenticatedInternalIndexRouteImport } from './routes/_authenticated/internal.index'
import { Route as AuthenticatedResourcesShellIndexRouteImport } from './routes/_authenticated/_resources/_shell/index'
import { Route as AuthenticatedResourcesShellAccountRouteImport } from './routes/_authenticated/_resources/_shell/account'
import { Route as AuthenticatedResourcesShellIntegrationsRouteImport } from './routes/_authenticated/_resources/_shell/integrations'
import { Route as AuthenticatedResourcesShellResourcesRouteImport } from './routes/_authenticated/_resources/_shell/resources'
import { Route as AuthenticatedResourcesShellSkillsRouteImport } from './routes/_authenticated/_resources/_shell/skills'
import { Route as AuthenticatedResourcesShellUsageRouteImport } from './routes/_authenticated/_resources/_shell/usage'
import { Route as AuthenticatedResourcesShellAgentsIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.index'
import { Route as AuthenticatedResourcesShellAgentsComputersRouteImport } from './routes/_authenticated/_resources/_shell/agents.computers'
import { Route as AuthenticatedResourcesShellAgentsNewRouteImport } from './routes/_authenticated/_resources/_shell/agents.new'
import { Route as AuthenticatedResourcesShellTasksIndexRouteImport } from './routes/_authenticated/_resources/_shell/tasks.index'
import { Route as AuthenticatedResourcesShellTasksTaskIdRouteImport } from './routes/_authenticated/_resources/_shell/tasks.$taskId'
import { Route as AuthenticatedResourcesShellAgentsAgentIdIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.index'
import { Route as AuthenticatedResourcesShellAgentsAgentIdLegacySectionRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.$legacySection'
import { Route as AuthenticatedResourcesShellAgentsAgentIdUsageRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.usage'
import { Route as AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.settings.index'
import { Route as AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRouteImport } from './routes/_authenticated/_resources/_shell/agents.$agentId.settings.$section'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/_resources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InternalOnboardingV2Route = InternalOnboardingV2RouteImport.update({
  id: '/internal/onboarding-v2',
  path: '/internal/onboarding-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResourcesShellRoute =
  AuthenticatedResourcesShellRouteImport.update({
    id: '/_shell',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedResourcesOnboardingRoute =
  AuthenticatedResourcesOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedResourcesRoute,
  } as any)
const AuthenticatedInternalIndexRoute =
  AuthenticatedInternalIndexRouteImport.update({
    id: '/internal/',
    path: '/internal/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResourcesShellIndexRoute =
  AuthenticatedResourcesShellIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAccountRoute =
  AuthenticatedResourcesShellAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellIntegrationsRoute =
  AuthenticatedResourcesShellIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellResourcesRoute =
  AuthenticatedResourcesShellResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellSkillsRoute =
  AuthenticatedResourcesShellSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellUsageRoute =
  AuthenticatedResourcesShellUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsIndexRoute =
  AuthenticatedResourcesShellAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsComputersRoute =
  AuthenticatedResourcesShellAgentsComputersRouteImport.update({
    id: '/agents/computers',
    path: '/agents/computers',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsNewRoute =
  AuthenticatedResourcesShellAgentsNewRouteImport.update({
    id: '/agents/new',
    path: '/agents/new',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellTasksIndexRoute =
  AuthenticatedResourcesShellTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellTasksTaskIdRoute =
  AuthenticatedResourcesShellTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsAgentIdIndexRoute =
  AuthenticatedResourcesShellAgentsAgentIdIndexRouteImport.update({
    id: '/agents/$agentId/',
    path: '/agents/$agentId/',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute =
  AuthenticatedResourcesShellAgentsAgentIdLegacySectionRouteImport.update({
    id: '/agents/$agentId/$legacySection',
    path: '/agents/$agentId/$legacySection',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsAgentIdUsageRoute =
  AuthenticatedResourcesShellAgentsAgentIdUsageRouteImport.update({
    id: '/agents/$agentId/usage',
    path: '/agents/$agentId/usage',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute =
  AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRouteImport.update({
    id: '/agents/$agentId/settings/',
    path: '/agents/$agentId/settings/',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)
const AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute =
  AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRouteImport.update({
    id: '/agents/$agentId/settings/$section',
    path: '/agents/$agentId/settings/$section',
    getParentRoute: () => AuthenticatedResourcesShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedResourcesShellIndexRoute
  '/login': typeof LoginRoute
  '/internal/onboarding-v2': typeof InternalOnboardingV2Route
  '/onboarding': typeof AuthenticatedResourcesOnboardingRoute
  '/internal/': typeof AuthenticatedInternalIndexRoute
  '/account': typeof AuthenticatedResourcesShellAccountRoute
  '/integrations': typeof AuthenticatedResourcesShellIntegrationsRoute
  '/resources': typeof AuthenticatedResourcesShellResourcesRoute
  '/skills': typeof AuthenticatedResourcesShellSkillsRoute
  '/usage': typeof AuthenticatedResourcesShellUsageRoute
  '/agents/computers': typeof AuthenticatedResourcesShellAgentsComputersRoute
  '/agents/new': typeof AuthenticatedResourcesShellAgentsNewRoute
  '/tasks/$taskId': typeof AuthenticatedResourcesShellTasksTaskIdRoute
  '/agents/': typeof AuthenticatedResourcesShellAgentsIndexRoute
  '/tasks/': typeof AuthenticatedResourcesShellTasksIndexRoute
  '/agents/$agentId/$legacySection': typeof AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute
  '/agents/$agentId/usage': typeof AuthenticatedResourcesShellAgentsAgentIdUsageRoute
  '/agents/$agentId/': typeof AuthenticatedResourcesShellAgentsAgentIdIndexRoute
  '/agents/$agentId/settings/$section': typeof AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute
  '/agents/$agentId/settings/': typeof AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedResourcesShellIndexRoute
  '/login': typeof LoginRoute
  '/internal/onboarding-v2': typeof InternalOnboardingV2Route
  '/onboarding': typeof AuthenticatedResourcesOnboardingRoute
  '/internal': typeof AuthenticatedInternalIndexRoute
  '/account': typeof AuthenticatedResourcesShellAccountRoute
  '/integrations': typeof AuthenticatedResourcesShellIntegrationsRoute
  '/resources': typeof AuthenticatedResourcesShellResourcesRoute
  '/skills': typeof AuthenticatedResourcesShellSkillsRoute
  '/usage': typeof AuthenticatedResourcesShellUsageRoute
  '/agents/computers': typeof AuthenticatedResourcesShellAgentsComputersRoute
  '/agents/new': typeof AuthenticatedResourcesShellAgentsNewRoute
  '/tasks/$taskId': typeof AuthenticatedResourcesShellTasksTaskIdRoute
  '/agents': typeof AuthenticatedResourcesShellAgentsIndexRoute
  '/tasks': typeof AuthenticatedResourcesShellTasksIndexRoute
  '/agents/$agentId/$legacySection': typeof AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute
  '/agents/$agentId/usage': typeof AuthenticatedResourcesShellAgentsAgentIdUsageRoute
  '/agents/$agentId': typeof AuthenticatedResourcesShellAgentsAgentIdIndexRoute
  '/agents/$agentId/settings/$section': typeof AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute
  '/agents/$agentId/settings': typeof AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_resources': typeof AuthenticatedResourcesRouteWithChildren
  '/internal/onboarding-v2': typeof InternalOnboardingV2Route
  '/_authenticated/_resources/_shell': typeof AuthenticatedResourcesShellRouteWithChildren
  '/_authenticated/_resources/onboarding': typeof AuthenticatedResourcesOnboardingRoute
  '/_authenticated/internal/': typeof AuthenticatedInternalIndexRoute
  '/_authenticated/_resources/_shell/account': typeof AuthenticatedResourcesShellAccountRoute
  '/_authenticated/_resources/_shell/integrations': typeof AuthenticatedResourcesShellIntegrationsRoute
  '/_authenticated/_resources/_shell/resources': typeof AuthenticatedResourcesShellResourcesRoute
  '/_authenticated/_resources/_shell/skills': typeof AuthenticatedResourcesShellSkillsRoute
  '/_authenticated/_resources/_shell/usage': typeof AuthenticatedResourcesShellUsageRoute
  '/_authenticated/_resources/_shell/': typeof AuthenticatedResourcesShellIndexRoute
  '/_authenticated/_resources/_shell/agents/computers': typeof AuthenticatedResourcesShellAgentsComputersRoute
  '/_authenticated/_resources/_shell/agents/new': typeof AuthenticatedResourcesShellAgentsNewRoute
  '/_authenticated/_resources/_shell/tasks/$taskId': typeof AuthenticatedResourcesShellTasksTaskIdRoute
  '/_authenticated/_resources/_shell/agents/': typeof AuthenticatedResourcesShellAgentsIndexRoute
  '/_authenticated/_resources/_shell/tasks/': typeof AuthenticatedResourcesShellTasksIndexRoute
  '/_authenticated/_resources/_shell/agents/$agentId/$legacySection': typeof AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute
  '/_authenticated/_resources/_shell/agents/$agentId/usage': typeof AuthenticatedResourcesShellAgentsAgentIdUsageRoute
  '/_authenticated/_resources/_shell/agents/$agentId/': typeof AuthenticatedResourcesShellAgentsAgentIdIndexRoute
  '/_authenticated/_resources/_shell/agents/$agentId/settings/$section': typeof AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute
  '/_authenticated/_resources/_shell/agents/$agentId/settings/': typeof AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/internal/onboarding-v2'
    | '/onboarding'
    | '/internal/'
    | '/account'
    | '/integrations'
    | '/resources'
    | '/skills'
    | '/usage'
    | '/agents/computers'
    | '/agents/new'
    | '/tasks/$taskId'
    | '/agents/'
    | '/tasks/'
    | '/agents/$agentId/$legacySection'
    | '/agents/$agentId/usage'
    | '/agents/$agentId/'
    | '/agents/$agentId/settings/$section'
    | '/agents/$agentId/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/internal/onboarding-v2'
    | '/onboarding'
    | '/internal'
    | '/account'
    | '/integrations'
    | '/resources'
    | '/skills'
    | '/usage'
    | '/agents/computers'
    | '/agents/new'
    | '/tasks/$taskId'
    | '/agents'
    | '/tasks'
    | '/agents/$agentId/$legacySection'
    | '/agents/$agentId/usage'
    | '/agents/$agentId'
    | '/agents/$agentId/settings/$section'
    | '/agents/$agentId/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_resources'
    | '/internal/onboarding-v2'
    | '/_authenticated/_resources/_shell'
    | '/_authenticated/_resources/onboarding'
    | '/_authenticated/internal/'
    | '/_authenticated/_resources/_shell/account'
    | '/_authenticated/_resources/_shell/integrations'
    | '/_authenticated/_resources/_shell/resources'
    | '/_authenticated/_resources/_shell/skills'
    | '/_authenticated/_resources/_shell/usage'
    | '/_authenticated/_resources/_shell/'
    | '/_authenticated/_resources/_shell/agents/computers'
    | '/_authenticated/_resources/_shell/agents/new'
    | '/_authenticated/_resources/_shell/tasks/$taskId'
    | '/_authenticated/_resources/_shell/agents/'
    | '/_authenticated/_resources/_shell/tasks/'
    | '/_authenticated/_resources/_shell/agents/$agentId/$legacySection'
    | '/_authenticated/_resources/_shell/agents/$agentId/usage'
    | '/_authenticated/_resources/_shell/agents/$agentId/'
    | '/_authenticated/_resources/_shell/agents/$agentId/settings/$section'
    | '/_authenticated/_resources/_shell/agents/$agentId/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  InternalOnboardingV2Route: typeof InternalOnboardingV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_resources': {
      id: '/_authenticated/_resources'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/internal/onboarding-v2': {
      id: '/internal/onboarding-v2'
      path: '/internal/onboarding-v2'
      fullPath: '/internal/onboarding-v2'
      preLoaderRoute: typeof InternalOnboardingV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_resources/_shell': {
      id: '/_authenticated/_resources/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedResourcesShellRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/_resources/onboarding': {
      id: '/_authenticated/_resources/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedResourcesOnboardingRouteImport
      parentRoute: typeof AuthenticatedResourcesRoute
    }
    '/_authenticated/internal/': {
      id: '/_authenticated/internal/'
      path: '/internal'
      fullPath: '/internal/'
      preLoaderRoute: typeof AuthenticatedInternalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_resources/_shell/': {
      id: '/_authenticated/_resources/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedResourcesShellIndexRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/account': {
      id: '/_authenticated/_resources/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedResourcesShellAccountRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/integrations': {
      id: '/_authenticated/_resources/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedResourcesShellIntegrationsRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/resources': {
      id: '/_authenticated/_resources/_shell/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesShellResourcesRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/skills': {
      id: '/_authenticated/_resources/_shell/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthenticatedResourcesShellSkillsRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/usage': {
      id: '/_authenticated/_resources/_shell/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AuthenticatedResourcesShellUsageRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/': {
      id: '/_authenticated/_resources/_shell/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/computers': {
      id: '/_authenticated/_resources/_shell/agents/computers'
      path: '/agents/computers'
      fullPath: '/agents/computers'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsComputersRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/new': {
      id: '/_authenticated/_resources/_shell/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsNewRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/tasks/': {
      id: '/_authenticated/_resources/_shell/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedResourcesShellTasksIndexRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/tasks/$taskId': {
      id: '/_authenticated/_resources/_shell/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedResourcesShellTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsAgentIdIndexRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/$legacySection': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/$legacySection'
      path: '/agents/$agentId/$legacySection'
      fullPath: '/agents/$agentId/$legacySection'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsAgentIdLegacySectionRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/usage': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/usage'
      path: '/agents/$agentId/usage'
      fullPath: '/agents/$agentId/usage'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsAgentIdUsageRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/settings/': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/settings/'
      path: '/agents/$agentId/settings'
      fullPath: '/agents/$agentId/settings/'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
    '/_authenticated/_resources/_shell/agents/$agentId/settings/$section': {
      id: '/_authenticated/_resources/_shell/agents/$agentId/settings/$section'
      path: '/agents/$agentId/settings/$section'
      fullPath: '/agents/$agentId/settings/$section'
      preLoaderRoute: typeof AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedResourcesShellRoute
    }
  }
}

interface AuthenticatedResourcesShellRouteChildren {
  AuthenticatedResourcesShellAccountRoute: typeof AuthenticatedResourcesShellAccountRoute
  AuthenticatedResourcesShellIntegrationsRoute: typeof AuthenticatedResourcesShellIntegrationsRoute
  AuthenticatedResourcesShellResourcesRoute: typeof AuthenticatedResourcesShellResourcesRoute
  AuthenticatedResourcesShellSkillsRoute: typeof AuthenticatedResourcesShellSkillsRoute
  AuthenticatedResourcesShellUsageRoute: typeof AuthenticatedResourcesShellUsageRoute
  AuthenticatedResourcesShellIndexRoute: typeof AuthenticatedResourcesShellIndexRoute
  AuthenticatedResourcesShellAgentsComputersRoute: typeof AuthenticatedResourcesShellAgentsComputersRoute
  AuthenticatedResourcesShellAgentsNewRoute: typeof AuthenticatedResourcesShellAgentsNewRoute
  AuthenticatedResourcesShellTasksTaskIdRoute: typeof AuthenticatedResourcesShellTasksTaskIdRoute
  AuthenticatedResourcesShellAgentsIndexRoute: typeof AuthenticatedResourcesShellAgentsIndexRoute
  AuthenticatedResourcesShellTasksIndexRoute: typeof AuthenticatedResourcesShellTasksIndexRoute
  AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute: typeof AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute
  AuthenticatedResourcesShellAgentsAgentIdUsageRoute: typeof AuthenticatedResourcesShellAgentsAgentIdUsageRoute
  AuthenticatedResourcesShellAgentsAgentIdIndexRoute: typeof AuthenticatedResourcesShellAgentsAgentIdIndexRoute
  AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute: typeof AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute
  AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute: typeof AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute
}

const AuthenticatedResourcesShellRouteChildren: AuthenticatedResourcesShellRouteChildren =
  {
    AuthenticatedResourcesShellAccountRoute:
      AuthenticatedResourcesShellAccountRoute,
    AuthenticatedResourcesShellIntegrationsRoute:
      AuthenticatedResourcesShellIntegrationsRoute,
    AuthenticatedResourcesShellResourcesRoute:
      AuthenticatedResourcesShellResourcesRoute,
    AuthenticatedResourcesShellSkillsRoute:
      AuthenticatedResourcesShellSkillsRoute,
    AuthenticatedResourcesShellUsageRoute:
      AuthenticatedResourcesShellUsageRoute,
    AuthenticatedResourcesShellIndexRoute:
      AuthenticatedResourcesShellIndexRoute,
    AuthenticatedResourcesShellAgentsComputersRoute:
      AuthenticatedResourcesShellAgentsComputersRoute,
    AuthenticatedResourcesShellAgentsNewRoute:
      AuthenticatedResourcesShellAgentsNewRoute,
    AuthenticatedResourcesShellTasksTaskIdRoute:
      AuthenticatedResourcesShellTasksTaskIdRoute,
    AuthenticatedResourcesShellAgentsIndexRoute:
      AuthenticatedResourcesShellAgentsIndexRoute,
    AuthenticatedResourcesShellTasksIndexRoute:
      AuthenticatedResourcesShellTasksIndexRoute,
    AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute:
      AuthenticatedResourcesShellAgentsAgentIdLegacySectionRoute,
    AuthenticatedResourcesShellAgentsAgentIdUsageRoute:
      AuthenticatedResourcesShellAgentsAgentIdUsageRoute,
    AuthenticatedResourcesShellAgentsAgentIdIndexRoute:
      AuthenticatedResourcesShellAgentsAgentIdIndexRoute,
    AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute:
      AuthenticatedResourcesShellAgentsAgentIdSettingsSectionRoute,
    AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute:
      AuthenticatedResourcesShellAgentsAgentIdSettingsIndexRoute,
  }

const AuthenticatedResourcesShellRouteWithChildren =
  AuthenticatedResourcesShellRoute._addFileChildren(
    AuthenticatedResourcesShellRouteChildren,
  )

interface AuthenticatedResourcesRouteChildren {
  AuthenticatedResourcesShellRoute: typeof AuthenticatedResourcesShellRouteWithChildren
  AuthenticatedResourcesOnboardingRoute: typeof AuthenticatedResourcesOnboardingRoute
}

const AuthenticatedResourcesRouteChildren: AuthenticatedResourcesRouteChildren =
  {
    AuthenticatedResourcesShellRoute:
      AuthenticatedResourcesShellRouteWithChildren,
    AuthenticatedResourcesOnboardingRoute:
      AuthenticatedResourcesOnboardingRoute,
  }

const AuthenticatedResourcesRouteWithChildren =
  AuthenticatedResourcesRoute._addFileChildren(
    AuthenticatedResourcesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRouteWithChildren
  AuthenticatedInternalIndexRoute: typeof AuthenticatedInternalIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedResourcesRoute: AuthenticatedResourcesRouteWithChildren,
  AuthenticatedInternalIndexRoute: AuthenticatedInternalIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  InternalOnboardingV2Route: InternalOnboardingV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
