/**
 * F6 cross-layer preparation contract, Web boundary.
 *
 * This suite consumes the shared plain-JSON scenario fixture
 * (`scripts/fixtures/onboarding-preparation-contract.json`) with `node:fs` relative to this file,
 * exactly like the CLI and Server contract suites do. Each scenario carries one canonical
 * exact-Agent `AgentSetupSnapshot` fixture authored independently of the F5 projector; this file
 * schema-parses that snapshot and projects it through the real F5 page logic
 * (`preparationReadinessRows`, `showPreparationSection`), then pins the canonical four-component
 * projection, the selected Runtime identity, and the messaging gate. Page-level cases separately
 * pin the same four individually visible checks.
 *
 * Nothing here is generated by the production projector and compared to itself: the expected rows
 * come from the fixture, and the fixture snapshot must stay valid under `AgentSetupSnapshotSchema`
 * on every run. The page-level cases below mount the real page over the schema-checked in-memory
 * model seeded from the same scenario facts; they are model tests, never a claim that the memory
 * adapter is the real Server E2E.
 *
 * The fixture also records the presentation limitation this surface must fail closed under: the
 * Server drops expired reports at TTL and exposes waiting with no old timestamp, so the Web cannot
 * distinguish a never-arrived report from an expired one and must not fabricate stale evidence.
 * Scenarios `no-fresh-observation` and `expired-observation` pin the identical waiting projection
 * from both facts, and every waiting row asserts Waiting — never Checking.
 */

import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { AgentSetupSnapshotSchema } from "@opentag/shared/browser";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AgentSetupPage } from "./agent-setup-page.js";
import { SETUP_AGENT_ID, setupAgent } from "./agent-setup-test-fixtures.js";
import { preparationReadinessRows, showPreparationSection } from "./preparation-readiness.js";
import type { CheckRow, ReadinessRows, ReadinessStatus } from "./readiness-list.js";
import type { MemorySetupSeed } from "./setup-memory-adapter.js";
import { createMemorySetupAdapter } from "./setup-memory-adapter.js";

const POLL_MS = 2_000;

interface FixtureRowExpectation {
  readonly component: "computer" | "runtime" | "im-cli:feishu" | "im-cli:slack";
  readonly state: "passed" | "pending" | "failed" | "blocked";
  readonly status: ReadinessStatus;
  readonly label?: string;
  readonly labelPart?: string;
  readonly statusLabel?: string;
}

interface FixtureScenario {
  readonly id: string;
  readonly runtimeProvider: "codex" | "claude-code";
  readonly local: {
    readonly facts: {
      readonly daemon: string;
    };
    readonly expected: { readonly localReady: boolean; readonly status: string };
  };
  readonly snapshot: unknown;
  readonly web: { readonly showPreparationSection: boolean; readonly rows: FixtureRowExpectation[] };
}

interface FixtureFile {
  readonly scenarios: FixtureScenario[];
}

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(resolve(here, "../../../../scripts/fixtures/onboarding-preparation-contract.json"), "utf8"),
) as FixtureFile;

const ROW_TO_PROJECTION = {
  computer: "computer",
  runtime: "runtime",
  "im-cli:feishu": "feishu",
  "im-cli:slack": "slack",
} as const;

function projectionRow(rows: ReadinessRows, component: FixtureRowExpectation["component"]): CheckRow {
  const row = rows[ROW_TO_PROJECTION[component]];
  if (!row) throw new Error(`Missing projected row for ${component}`);
  return row;
}

async function settle(rounds = 6): Promise<void> {
  await act(async () => {
    for (let index = 0; index < rounds; index += 1) await Promise.resolve();
  });
}

async function advance(ms: number): Promise<void> {
  await act(async () => {
    await vi.advanceTimersByTimeAsync(ms);
  });
}

function renderSetup(seed: MemorySetupSeed) {
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  const memory = createMemorySetupAdapter(seed);
  const view = render(
    <QueryClientProvider client={queryClient}>
      <AgentSetupPage adapter={memory.adapter} agentId={SETUP_AGENT_ID} />
    </QueryClientProvider>,
  );
  return { memory, view };
}

function readinessRow(component: string): HTMLElement {
  const element = document.querySelector(`[data-ui="readiness-list"] [data-component="${component}"]`);
  if (!element) throw new Error(`Missing readiness row for ${component}`);
  return element as HTMLElement;
}

function rowTitle(component: string): string {
  return readinessRow(component).querySelector('[data-ui="readiness-title"]')?.textContent ?? "";
}

function rowDetail(component: string): string {
  return readinessRow(component).querySelector('[data-ui="readiness-detail"]')?.textContent ?? "";
}

/** Step 2 keeps all four authoritative checks individually visible. */
function expectPreparationRows(): void {
  const list = document.querySelector('[data-ui="readiness-list"]');
  expect(list).not.toBeNull();
  const items = within(list as HTMLElement).getAllByRole("listitem");
  expect(items.map((item) => item.getAttribute("data-component"))).toEqual([
    "computer",
    "runtime",
    "im-cli:feishu",
    "im-cli:slack",
  ]);
}

beforeEach(() => {
  vi.useFakeTimers();
});

afterEach(() => {
  vi.restoreAllMocks();
  vi.useRealTimers();
});

describe("F6 shared preparation matrix, Web projection", () => {
  it.each(fixture.scenarios.map((scenario) => [scenario.id, scenario] as const))(
    "scenario %s projects its canonical snapshot through the real F5 page logic",
    (_id, scenario) => {
      // The fixture snapshot is canonical only if the shared contract accepts it unchanged.
      const snapshot = AgentSetupSnapshotSchema.parse(scenario.snapshot);
      const rows = preparationReadinessRows(snapshot);
      expect(showPreparationSection(snapshot)).toBe(scenario.web.showPreparationSection);

      expect(scenario.web.rows).toHaveLength(4);
      for (const expected of scenario.web.rows) {
        const row = projectionRow(rows, expected.component);
        expect(row.state, `${expected.component} state`).toBe(expected.state);
        expect(row.status, `${expected.component} status`).toBe(expected.status);
        if (expected.label !== undefined) {
          expect(row.label, `${expected.component} label`).toBe(expected.label);
        }
        if (expected.labelPart !== undefined) {
          expect(row.label, `${expected.component} label contains`).toContain(expected.labelPart);
        }
        if (expected.statusLabel !== undefined) {
          expect(row.statusLabel, `${expected.component} statusLabel`).toBe(expected.statusLabel);
        }
        if (expected.status === "ready") {
          // A ready row owns its exact ready label and never carries a status label.
          expect(row.label).toMatch(/ ready$/);
          expect(row.statusLabel).toBe("");
        }
      }
    },
  );

  it("pins the selected Runtime identity per scenario in the ready label vocabulary", () => {
    const codex = fixture.scenarios.find((scenario) => scenario.id === "success-codex");
    const claude = fixture.scenarios.find((scenario) => scenario.id === "success-claude-code");
    expect(codex).toBeDefined();
    expect(claude).toBeDefined();
    const codexRows = preparationReadinessRows(AgentSetupSnapshotSchema.parse(codex?.snapshot));
    const claudeRows = preparationReadinessRows(AgentSetupSnapshotSchema.parse(claude?.snapshot));
    expect(codexRows.runtime.label).toBe("Codex ready");
    expect(claudeRows.runtime.label).toBe("Claude Code ready");
    expect(codexRows.computer.label).toBe("Computer ready");
    expect(codexRows.feishu.label).toBe("Lark CLI ready");
    expect(codexRows.slack.label).toBe("Slack CLI ready");
  });

  it("keeps missing and expired observations identical fail-closed waiting rows, never Checking", () => {
    const missing = fixture.scenarios.find((scenario) => scenario.id === "no-fresh-observation");
    const expired = fixture.scenarios.find((scenario) => scenario.id === "expired-observation");
    expect(missing).toBeDefined();
    expect(expired).toBeDefined();
    const missingSnapshot = AgentSetupSnapshotSchema.parse(missing?.snapshot);
    const expiredSnapshot = AgentSetupSnapshotSchema.parse(expired?.snapshot);
    // Both Server facts (report never arrived / report dropped by TTL) must project identically:
    // the Web cannot distinguish them and never invents stale/expired authority.
    expect(expiredSnapshot).toEqual(missingSnapshot);
    const rows = preparationReadinessRows(missingSnapshot);
    for (const row of [rows.runtime, rows.feishu, rows.slack]) {
      expect(row.state).toBe("pending");
      expect(row.status).toBe("waiting");
      expect(row.statusLabel).toBe("Waiting");
      // The waiting copy may honestly explain that a report may have expired, but it never
      // claims a check or install is happening and never asserts stale authority.
      expect(row.detail).not.toMatch(/checking the|installing|stale/i);
    }
    // The Server snapshot carries no old timestamp for these legs: waiting is evidence-less.
    for (const component of missingSnapshot.components) {
      if (component.kind === "runtime" || component.kind === "im-cli") {
        expect(component.observedAt).toBeNull();
      }
    }
    expect(missingSnapshot.actions).toEqual([{ kind: "refresh" }]);
  });

  it("renders a fresh missing-Runtime report as installation required, never installation in progress", () => {
    const scenario = fixture.scenarios.find((candidate) => candidate.id === "runtime-missing-codex");
    if (!scenario) throw new Error("missing runtime-missing-codex scenario");
    const snapshot = AgentSetupSnapshotSchema.parse(scenario.snapshot);
    expect(snapshot.runtime.kind).toBe("observed");
    const row = preparationReadinessRows(snapshot).runtime;
    expect(row.status).toBe("install-required");
    expect(row.statusLabel).toBe("Installation required");
    expect(row.detail).toContain("OpenTag won't install it for you");
    expect(row.detail).not.toMatch(/installing|checking the/i);
    expect(snapshot.actions).toEqual([{ kind: "refresh" }]);
  });

  it("keeps a real checking observation checking and never invents one from waiting", () => {
    const checking = fixture.scenarios.find((scenario) => scenario.id === "checking-ownership");
    const waiting = fixture.scenarios.find((scenario) => scenario.id === "no-fresh-observation");
    expect(checking).toBeDefined();
    expect(waiting).toBeDefined();
    const checkingRows = preparationReadinessRows(AgentSetupSnapshotSchema.parse(checking?.snapshot));
    const waitingRows = preparationReadinessRows(AgentSetupSnapshotSchema.parse(waiting?.snapshot));
    expect(checkingRows.feishu.status).toBe("checking");
    expect(checkingRows.feishu.statusLabel).toBe("Checking");
    expect(waitingRows.feishu.status).toBe("waiting");
    expect(waitingRows.feishu.statusLabel).toBe("Waiting");
  });
});

describe("F6 cross-layer gating, page level", () => {
  it("keeps a local-ready world gated until fresh daemon reports open the Server stage", async () => {
    const scenario = fixture.scenarios.find((candidate) => candidate.id === "no-fresh-observation");
    if (!scenario) throw new Error("missing no-fresh-observation scenario");
    // Cross-layer premise, pinned from the same fixture: the CLI local result is ready...
    expect(scenario.local.expected.localReady).toBe(true);
    expect(scenario.local.expected.status).toBe("ready");
    // ...while the Server has no fresh observation yet, so the canonical snapshot stays gated.
    const snapshot = AgentSetupSnapshotSchema.parse(scenario.snapshot);
    expect(snapshot.stage).toBe("needs-runtime");
    expect(snapshot.actions).toEqual([{ kind: "refresh" }]);

    // The page is fed the Server side of the same scenario: online Computer, no reports yet.
    const { memory } = renderSetup({
      agent: setupAgent(),
      runtimeMissing: true,
      imCliReadiness: {},
    });
    await settle();

    expect(screen.queryByRole("heading", { name: "Connect your messaging app" })).toBeNull();
    expectPreparationRows();
    for (const component of ["runtime", "im-cli:feishu", "im-cli:slack"]) {
      expect(readinessRow(component).getAttribute("data-state")).toBe("pending");
      expect(readinessRow(component).getAttribute("data-status")).toBe("waiting");
      expect(rowTitle(component)).toContain("Waiting");
    }
    expect(rowTitle("runtime")).toContain("Codex");
    expect(rowTitle("im-cli:feishu")).toContain("Lark CLI");
    expect(rowTitle("im-cli:slack")).toContain("Slack CLI");
    expect(screen.queryByText("Checking")).toBeNull();
    expect(screen.queryByText("Installing")).toBeNull();
    expect(screen.queryByText("Installation required")).toBeNull();

    // Fresh daemon observations arrive; the same page must then open the Messaging gate.
    memory.controls.setRuntimeStatus("ready");
    memory.controls.setImCliReadiness("feishu", "ready");
    memory.controls.setImCliReadiness("slack", "ready");
    await advance(POLL_MS + 10);
    await settle();

    expect(screen.getByRole("heading", { name: "Connect your messaging app" })).toBeTruthy();
    expect(document.querySelector('[data-ui="readiness-list"]')).toBeNull();
    expect(screen.getByRole("button", { name: /Your Slack workspace/ })).toBeTruthy();
  });

  it("never lets an unselected Provider's later report regress an underway Messaging handoff", async () => {
    const scenario = fixture.scenarios.find((candidate) => candidate.id === "messaging-underway-slack");
    if (!scenario) throw new Error("missing messaging-underway-slack scenario");
    const snapshot = AgentSetupSnapshotSchema.parse(scenario.snapshot);
    // Canonical premise: Messaging already started (Slack waiting-handoff), so the preparation
    // section is off the page even though the unselected Lark leg has no fresh report yet.
    if (snapshot.messaging.kind !== "waiting-handoff") {
      throw new Error("messaging-underway fixture must carry a waiting-handoff");
    }
    expect(snapshot.messaging.provider).toBe("slack");
    expect(showPreparationSection(snapshot)).toBe(false);

    const { memory } = renderSetup({
      agent: setupAgent(),
      messaging: { kind: "bound", provider: "slack" },
      imCliReadiness: { feishu: "install", slack: "ready" },
    });
    await settle();

    // The handoff surface owns Messaging; CLI readiness rows left the page entirely.
    expect(document.querySelector('[data-ui="readiness-list"]')).toBeNull();
    expect(screen.getByText("Connected. Checking your agent can be reached…")).toBeTruthy();
    const messaging = document.querySelector('[data-ui="agent-setup-messaging"]') as HTMLElement | null;
    expect(messaging?.textContent).not.toMatch(/CLI|Installation required|Waiting for Computer/);

    // The unselected Provider's report keeps changing after Messaging started: none of it may
    // bring the four rows back or gate the handoff.
    memory.controls.setImCliReadiness("feishu", "checking");
    await advance(POLL_MS + 10);
    await settle();
    expect(document.querySelector('[data-ui="readiness-list"]')).toBeNull();
    expect(screen.getByText("Connected. Checking your agent can be reached…")).toBeTruthy();

    memory.controls.setImCliReadiness("feishu", "ready");
    await advance(POLL_MS + 10);
    await settle();
    expect(document.querySelector('[data-ui="readiness-list"]')).toBeNull();
    expect(screen.getByText("Connected. Checking your agent can be reached…")).toBeTruthy();
  });

  it("renders the successful summary rows before Messaging starts and never fabricates progress", async () => {
    const scenario = fixture.scenarios.find((candidate) => candidate.id === "success-codex");
    if (!scenario) throw new Error("missing success-codex scenario");
    const { memory } = renderSetup({
      agent: setupAgent(),
      imCliReadiness: { feishu: "ready", slack: "ready" },
    });
    await settle();

    const snapshot = await memory.adapter.readSnapshot(SETUP_AGENT_ID);
    const rows = preparationReadinessRows(snapshot);
    expect(snapshot.stage).toBe("needs-messaging");
    expect(rows.computer.label).toBe("Computer ready");
    expect(rows.runtime.label).toBe("Codex ready");
    expect(rows.feishu.label).toBe("Lark CLI ready");
    expect(rows.slack.label).toBe("Slack CLI ready");
    const messaging = document.querySelector('[data-ui="agent-setup-messaging"]') as HTMLElement;
    expect(messaging.textContent).not.toMatch(/CLI|Installation required|Checking|Waiting for Computer/);
    // No row claims a CLI is being checked or installed anywhere on the ready surface.
    expect(screen.queryByText("Checking")).toBeNull();
    expect(screen.queryByText("Installing")).toBeNull();
  });

  it("keeps messaging unstartable while a required row waits and Check again is the honest move", async () => {
    const scenario = fixture.scenarios.find((candidate) => candidate.id === "lark-cli-failure");
    if (!scenario) throw new Error("missing lark-cli-failure scenario");
    const { memory } = renderSetup({
      agent: setupAgent(),
      imCliReadiness: { feishu: "unavailable", slack: "ready" },
    });
    await settle();

    const snapshot = await memory.adapter.readSnapshot(SETUP_AGENT_ID);
    expect(snapshot.stage).toBe("needs-provider-clis");
    expect(snapshot.actions).toEqual([{ kind: "refresh" }]);
    expect(screen.queryByRole("heading", { name: "Connect your messaging app" })).toBeNull();
    expectPreparationRows();
    expect(readinessRow("im-cli:feishu").getAttribute("data-state")).toBe("failed");
    expect(readinessRow("im-cli:feishu").getAttribute("data-status")).toBe("needs-attention");
    expect(rowTitle("im-cli:feishu")).toContain("Lark CLI");
    expect(rowTitle("im-cli:feishu")).toContain("Needs attention");
    expect(rowDetail("im-cli:feishu")).toContain("Continue the repair in the coding agent on Review Mac");
    expect(readinessRow("im-cli:slack").getAttribute("data-status")).toBe("ready");
    // The row never fabricates a checking state for an unavailable report.
    expect(rowTitle("im-cli:feishu")).not.toContain("Checking");
    expect(screen.getByRole("button", { name: "Check again" })).toBeTruthy();
    // A manual Check again is the only page move: it re-reads; nothing installs anything.
    const reads = vi.spyOn(memory.adapter, "readSnapshot");
    fireEvent.click(screen.getByRole("button", { name: "Check again" }));
    await settle();
    expect(reads).toHaveBeenCalled();
    expect(screen.queryByText("Installing")).toBeNull();
  });
});
