/**
 * Generated by scripts/generate-mcp-catalog.mjs from mcp-categories.yaml and mcp-catalog.yaml.
 * Do not edit by hand. Run `pnpm catalog:generate`.
 */
import type { MCPAuthKind } from "@opentag/shared/browser";
import exaIconUrl from "../../../assets/mcp/exa.svg";
import gmailIconUrl from "../../../assets/mcp/gmail.svg";
import googleCalendarIconUrl from "../../../assets/mcp/google-calendar.svg";
import googleChatIconUrl from "../../../assets/mcp/google-chat.svg";
import googleDocsIconUrl from "../../../assets/mcp/google-docs.svg";
import googleDriveIconUrl from "../../../assets/mcp/google-drive.svg";
import googlePeopleIconUrl from "../../../assets/mcp/google-people.svg";
import googleSheetsIconUrl from "../../../assets/mcp/google-sheets.svg";
import googleSlidesIconUrl from "../../../assets/mcp/google-slides.svg";
import linearIconUrl from "../../../assets/mcp/linear.svg";
import notionIconUrl from "../../../assets/mcp/notion.svg";
import sentryIconUrl from "../../../assets/mcp/sentry.svg";
import type { Locale } from "../../../i18n/locale.js";

/** Card and tab copy. Every supported locale is required, so a card never falls back silently. */
export type McpCatalogLocalizedText = Record<Locale, string>;

export type McpCatalogCategory = {
  id: string;
  label: McpCatalogLocalizedText;
  order: number;
};

export type McpCatalogEntry = {
  id: string;
  name: string;
  title: McpCatalogLocalizedText;
  description: McpCatalogLocalizedText;
  url: string;
  defaultAuthKind: MCPAuthKind;
  authHeader?: string;
  authScheme?: string;
  extraHeaders?: Record<string, string>;
  oauthScopes?: string[];
  category: string;
  website: string;
  iconUrl: string;
  order: number;
};

/** Tab order is this array's order. */
export const MCP_CATALOG_CATEGORIES: readonly McpCatalogCategory[] = [
  {
    id: "general",
    label: {
      en: "General",
      zh: "通用",
    },
    order: 10,
  },
  {
    id: "engineering",
    label: {
      en: "Engineering",
      zh: "工程",
    },
    order: 20,
  },
  {
    id: "google-workspace",
    label: {
      en: "Google Workspace",
      zh: "Google Workspace",
    },
    order: 30,
  },
];

/** Grouped by category order, then entry order. */
export const MCP_CATALOG_ENTRIES: readonly McpCatalogEntry[] = [
  {
    id: "notion",
    name: "notion",
    title: {
      en: "Notion",
      zh: "Notion",
    },
    description: {
      en: "Docs, wikis, and project pages.",
      zh: "文档、知识库与项目页面。",
    },
    url: "https://mcp.notion.com/mcp",
    defaultAuthKind: "oauth",
    category: "general",
    website: "https://www.notion.com",
    iconUrl: notionIconUrl,
    order: 10,
  },
  {
    id: "exa",
    name: "exa",
    title: {
      en: "Exa",
      zh: "Exa",
    },
    description: {
      en: "Web search and research.",
      zh: "网页搜索与研究。",
    },
    url: "https://mcp.exa.ai/mcp",
    defaultAuthKind: "none",
    category: "general",
    website: "https://exa.ai",
    iconUrl: exaIconUrl,
    order: 20,
  },
  {
    id: "linear",
    name: "linear",
    title: {
      en: "Linear",
      zh: "Linear",
    },
    description: {
      en: "Issues, projects, and cycles.",
      zh: "事务、项目与迭代。",
    },
    url: "https://mcp.linear.app/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://linear.app",
    iconUrl: linearIconUrl,
    order: 10,
  },
  {
    id: "sentry",
    name: "sentry",
    title: {
      en: "Sentry",
      zh: "Sentry",
    },
    description: {
      en: "Errors, traces, and releases.",
      zh: "错误、链路追踪与发布。",
    },
    url: "https://mcp.sentry.dev/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://sentry.io",
    iconUrl: sentryIconUrl,
    order: 20,
  },
  {
    id: "gmail",
    name: "gmail",
    title: {
      en: "Gmail",
      zh: "Gmail",
    },
    description: {
      en: "Read, search, and draft email.",
      zh: "阅读、搜索和起草邮件。",
    },
    url: "https://gmailmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: ["https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.compose"],
    category: "google-workspace",
    website: "https://workspace.google.com/products/gmail/",
    iconUrl: gmailIconUrl,
    order: 10,
  },
  {
    id: "google-drive",
    name: "google-drive",
    title: {
      en: "Google Drive",
      zh: "Google Drive",
    },
    description: {
      en: "Find, read, and manage files.",
      zh: "查找、读取和管理文件。",
    },
    url: "https://drivemcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: ["https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/drive.file"],
    category: "google-workspace",
    website: "https://workspace.google.com/products/drive/",
    iconUrl: googleDriveIconUrl,
    order: 20,
  },
  {
    id: "google-docs",
    name: "google-docs",
    title: {
      en: "Google Docs",
      zh: "Google Docs",
    },
    description: {
      en: "Read and edit documents.",
      zh: "读取和编辑文档。",
    },
    url: "https://docsmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/documents.readonly",
      "https://www.googleapis.com/auth/documents",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/docs/",
    iconUrl: googleDocsIconUrl,
    order: 30,
  },
  {
    id: "google-sheets",
    name: "google-sheets",
    title: {
      en: "Google Sheets",
      zh: "Google Sheets",
    },
    description: {
      en: "Read and update spreadsheets.",
      zh: "读取和更新电子表格。",
    },
    url: "https://sheetsmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/spreadsheets.readonly",
      "https://www.googleapis.com/auth/spreadsheets",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/sheets/",
    iconUrl: googleSheetsIconUrl,
    order: 40,
  },
  {
    id: "google-slides",
    name: "google-slides",
    title: {
      en: "Google Slides",
      zh: "Google Slides",
    },
    description: {
      en: "Read and edit presentations.",
      zh: "读取和编辑演示文稿。",
    },
    url: "https://slidesmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/presentations.readonly",
      "https://www.googleapis.com/auth/presentations",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/slides/",
    iconUrl: googleSlidesIconUrl,
    order: 50,
  },
  {
    id: "google-calendar",
    name: "google-calendar",
    title: {
      en: "Google Calendar",
      zh: "Google Calendar",
    },
    description: {
      en: "View and manage events and calendars.",
      zh: "查看和管理日程与日历。",
    },
    url: "https://calendarmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
      "https://www.googleapis.com/auth/calendar.events.freebusy",
      "https://www.googleapis.com/auth/calendar.events.readonly",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/calendar/",
    iconUrl: googleCalendarIconUrl,
    order: 60,
  },
  {
    id: "google-chat",
    name: "google-chat",
    title: {
      en: "Google Chat",
      zh: "Google Chat",
    },
    description: {
      en: "Search conversations and send messages.",
      zh: "搜索会话并发送消息。",
    },
    url: "https://chatmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/chat.spaces.readonly",
      "https://www.googleapis.com/auth/chat.memberships.readonly",
      "https://www.googleapis.com/auth/chat.messages.readonly",
      "https://www.googleapis.com/auth/chat.messages.create",
      "https://www.googleapis.com/auth/chat.users.readstate",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/chat/",
    iconUrl: googleChatIconUrl,
    order: 70,
  },
  {
    id: "google-people",
    name: "google-people",
    title: {
      en: "People",
      zh: "People",
    },
    description: {
      en: "Look up profiles, contacts, and directory people.",
      zh: "查询个人资料、联系人和目录成员。",
    },
    url: "https://people.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/directory.readonly",
      "https://www.googleapis.com/auth/userinfo.profile",
      "https://www.googleapis.com/auth/contacts.readonly",
    ],
    category: "google-workspace",
    website: "https://developers.google.com/people",
    iconUrl: googlePeopleIconUrl,
    order: 80,
  },
];
