/**
 * Generated by scripts/generate-mcp-catalog.mjs from mcp-categories.yaml and mcp-catalog.yaml.
 * Do not edit by hand. Run `pnpm catalog:generate`.
 */
import type { MCPAuthKind } from "@opentag/shared/browser";
import exaIconUrl from "../../../assets/mcp/exa.svg";
import linearIconUrl from "../../../assets/mcp/linear.svg";
import notionIconUrl from "../../../assets/mcp/notion.svg";
import sentryIconUrl from "../../../assets/mcp/sentry.svg";
import type { Locale } from "../../../i18n/locale.js";

/** Card and tab copy. Every supported locale is required, so a card never falls back silently. */
export type McpCatalogLocalizedText = Record<Locale, string>;

export type McpCatalogCategory = {
  id: string;
  label: McpCatalogLocalizedText;
  order: number;
};

export type McpCatalogEntry = {
  id: string;
  name: string;
  title: McpCatalogLocalizedText;
  description: McpCatalogLocalizedText;
  url: string;
  defaultAuthKind: MCPAuthKind;
  authHeader?: string;
  authScheme?: string;
  extraHeaders?: Record<string, string>;
  category: string;
  website: string;
  iconUrl: string;
  order: number;
};

/** Tab order is this array's order. */
export const MCP_CATALOG_CATEGORIES: readonly McpCatalogCategory[] = [
  {
    id: "general",
    label: {
      en: "General",
      zh: "通用",
    },
    order: 10,
  },
  {
    id: "engineering",
    label: {
      en: "Engineering",
      zh: "工程",
    },
    order: 20,
  },
];

/** Grouped by category order, then entry order. */
export const MCP_CATALOG_ENTRIES: readonly McpCatalogEntry[] = [
  {
    id: "notion",
    name: "notion",
    title: {
      en: "Notion",
      zh: "Notion",
    },
    description: {
      en: "Docs, wikis, and project pages.",
      zh: "文档、知识库与项目页面。",
    },
    url: "https://mcp.notion.com/mcp",
    defaultAuthKind: "oauth",
    category: "general",
    website: "https://www.notion.com",
    iconUrl: notionIconUrl,
    order: 10,
  },
  {
    id: "exa",
    name: "exa",
    title: {
      en: "Exa",
      zh: "Exa",
    },
    description: {
      en: "Web search and research.",
      zh: "网页搜索与研究。",
    },
    url: "https://mcp.exa.ai/mcp",
    defaultAuthKind: "none",
    category: "general",
    website: "https://exa.ai",
    iconUrl: exaIconUrl,
    order: 20,
  },
  {
    id: "linear",
    name: "linear",
    title: {
      en: "Linear",
      zh: "Linear",
    },
    description: {
      en: "Issues, projects, and cycles.",
      zh: "事务、项目与迭代。",
    },
    url: "https://mcp.linear.app/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://linear.app",
    iconUrl: linearIconUrl,
    order: 10,
  },
  {
    id: "sentry",
    name: "sentry",
    title: {
      en: "Sentry",
      zh: "Sentry",
    },
    description: {
      en: "Errors, traces, and releases.",
      zh: "错误、链路追踪与发布。",
    },
    url: "https://mcp.sentry.dev/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://sentry.io",
    iconUrl: sentryIconUrl,
    order: 20,
  },
];
