/**
 * Generated by scripts/generate-mcp-catalog.mjs from mcp-categories.yaml, mcp-catalog.yaml, and icons/*.
 * Do not edit by hand. Run `pnpm catalog:generate`.
 */
import type { MCPAuthKind } from "@opentag/shared/browser";

/** The locales the Web App supports, taken from its i18n project settings. */
export type McpCatalogLocale = "en" | "zh";

/** Card and tab copy. Every supported locale is required, so a card never falls back silently. */
export type McpCatalogLocalizedText = Record<McpCatalogLocale, string>;

/** The card marks, embedded as data URLs: one declaration per distinct icon file. */
export const MCP_CATALOG_ICON_URLS = {
  "airtable.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5BPC90ZXh0Pjwvc3ZnPgo=",
  "amplitude.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5BPC90ZXh0Pjwvc3ZnPgo=",
  "asana.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5BPC90ZXh0Pjwvc3ZnPgo=",
  "atlassian.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5BPC90ZXh0Pjwvc3ZnPgo=",
  "canva.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5DPC90ZXh0Pjwvc3ZnPgo=",
  "exa.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5FPC90ZXh0Pjwvc3ZnPgo=",
  "figma.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5GPC90ZXh0Pjwvc3ZnPgo=",
  "firecrawl.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPkZjPC90ZXh0Pjwvc3ZnPgo=",
  "gmail.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5NPC90ZXh0Pjwvc3ZnPgo=",
  "google-calendar.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5DPC90ZXh0Pjwvc3ZnPgo=",
  "google-chat.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPkNoPC90ZXh0Pjwvc3ZnPgo=",
  "google-docs.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPkRvPC90ZXh0Pjwvc3ZnPgo=",
  "google-drive.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPkRyPC90ZXh0Pjwvc3ZnPgo=",
  "google-people.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5QPC90ZXh0Pjwvc3ZnPgo=",
  "google-sheets.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPlNoPC90ZXh0Pjwvc3ZnPgo=",
  "google-slides.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPlNsPC90ZXh0Pjwvc3ZnPgo=",
  "hubspot.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTUuNCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSI5IiBmb250LXdlaWdodD0iNzAwIiBmaWxsPSJjdXJyZW50Q29sb3IiPkhzPC90ZXh0Pjwvc3ZnPgo=",
  "linear.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5MPC90ZXh0Pjwvc3ZnPgo=",
  "microsoft-365.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5NPC90ZXh0Pjwvc3ZnPgo=",
  "monday.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5NPC90ZXh0Pjwvc3ZnPgo=",
  "notion.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5OPC90ZXh0Pjwvc3ZnPgo=",
  "sentry.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5TPC90ZXh0Pjwvc3ZnPgo=",
  "stripe.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5TPC90ZXh0Pjwvc3ZnPgo=",
  "supabase.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5TPC90ZXh0Pjwvc3ZnPgo=",
  "tavily.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5UPC90ZXh0Pjwvc3ZnPgo=",
  "zapier.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5aPC90ZXh0Pjwvc3ZnPgo=",
} as const;

export type McpCatalogCategory = {
  id: string;
  label: McpCatalogLocalizedText;
  order: number;
};

export type McpCatalogEntry = {
  id: string;
  name: string;
  title: McpCatalogLocalizedText;
  description: McpCatalogLocalizedText;
  url: string;
  defaultAuthKind: MCPAuthKind;
  authHeader?: string;
  authScheme?: string;
  extraHeaders?: Record<string, string>;
  oauthScopes?: string[];
  category: string;
  website: string;
  iconUrl: string;
  order: number;
};

/** Tab order is this array's order. */
export const MCP_CATALOG_CATEGORIES: readonly McpCatalogCategory[] = [
  {
    id: "general",
    label: {
      en: "General",
      zh: "通用",
    },
    order: 10,
  },
  {
    id: "engineering",
    label: {
      en: "Engineering",
      zh: "工程",
    },
    order: 20,
  },
  {
    id: "google-workspace",
    label: {
      en: "Google Workspace",
      zh: "Google Workspace",
    },
    order: 30,
  },
  {
    id: "productivity",
    label: {
      en: "Productivity",
      zh: "生产力",
    },
    order: 40,
  },
  {
    id: "design",
    label: {
      en: "Design",
      zh: "设计",
    },
    order: 50,
  },
  {
    id: "search",
    label: {
      en: "Search",
      zh: "搜索",
    },
    order: 60,
  },
  {
    id: "automation",
    label: {
      en: "Automation",
      zh: "自动化",
    },
    order: 70,
  },
  {
    id: "business-data",
    label: {
      en: "Business & Data",
      zh: "业务与数据",
    },
    order: 80,
  },
];

/** Grouped by category order, then entry order. */
export const MCP_CATALOG_ENTRIES: readonly McpCatalogEntry[] = [
  {
    id: "notion",
    name: "notion",
    title: {
      en: "Notion",
      zh: "Notion",
    },
    description: {
      en: "Docs, wikis, and project pages.",
      zh: "文档、知识库与项目页面。",
    },
    url: "https://mcp.notion.com/mcp",
    defaultAuthKind: "oauth",
    category: "general",
    website: "https://www.notion.com",
    iconUrl: MCP_CATALOG_ICON_URLS["notion.svg"],
    order: 10,
  },
  {
    id: "exa",
    name: "exa",
    title: {
      en: "Exa",
      zh: "Exa",
    },
    description: {
      en: "Web search and research.",
      zh: "网页搜索与研究。",
    },
    url: "https://mcp.exa.ai/mcp",
    defaultAuthKind: "none",
    category: "general",
    website: "https://exa.ai",
    iconUrl: MCP_CATALOG_ICON_URLS["exa.svg"],
    order: 20,
  },
  {
    id: "linear",
    name: "linear",
    title: {
      en: "Linear",
      zh: "Linear",
    },
    description: {
      en: "Issues, projects, and cycles.",
      zh: "事务、项目与迭代。",
    },
    url: "https://mcp.linear.app/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://linear.app",
    iconUrl: MCP_CATALOG_ICON_URLS["linear.svg"],
    order: 10,
  },
  {
    id: "sentry",
    name: "sentry",
    title: {
      en: "Sentry",
      zh: "Sentry",
    },
    description: {
      en: "Errors, traces, and releases.",
      zh: "错误、链路追踪与发布。",
    },
    url: "https://mcp.sentry.dev/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://sentry.io",
    iconUrl: MCP_CATALOG_ICON_URLS["sentry.svg"],
    order: 20,
  },
  {
    id: "atlassian",
    name: "atlassian",
    title: {
      en: "Atlassian",
      zh: "Atlassian",
    },
    description: {
      en: "Jira issues, Confluence pages, and team knowledge.",
      zh: "Jira 事务、Confluence 页面与团队知识。",
    },
    url: "https://mcp.atlassian.com/v2/mcp?tools=all",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://www.atlassian.com",
    iconUrl: MCP_CATALOG_ICON_URLS["atlassian.svg"],
    order: 30,
  },
  {
    id: "gmail",
    name: "gmail",
    title: {
      en: "Gmail",
      zh: "Gmail",
    },
    description: {
      en: "Read, search, and draft email.",
      zh: "阅读、搜索和起草邮件。",
    },
    url: "https://gmailmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: ["https://www.googleapis.com/auth/gmail.readonly", "https://www.googleapis.com/auth/gmail.compose"],
    category: "google-workspace",
    website: "https://workspace.google.com/products/gmail/",
    iconUrl: MCP_CATALOG_ICON_URLS["gmail.svg"],
    order: 10,
  },
  {
    id: "google-drive",
    name: "google-drive",
    title: {
      en: "Google Drive",
      zh: "Google Drive",
    },
    description: {
      en: "Find, read, and manage files.",
      zh: "查找、读取和管理文件。",
    },
    url: "https://drivemcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: ["https://www.googleapis.com/auth/drive.readonly", "https://www.googleapis.com/auth/drive.file"],
    category: "google-workspace",
    website: "https://workspace.google.com/products/drive/",
    iconUrl: MCP_CATALOG_ICON_URLS["google-drive.svg"],
    order: 20,
  },
  {
    id: "google-docs",
    name: "google-docs",
    title: {
      en: "Google Docs",
      zh: "Google Docs",
    },
    description: {
      en: "Read and edit documents.",
      zh: "读取和编辑文档。",
    },
    url: "https://docsmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/documents.readonly",
      "https://www.googleapis.com/auth/documents",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/docs/",
    iconUrl: MCP_CATALOG_ICON_URLS["google-docs.svg"],
    order: 30,
  },
  {
    id: "google-sheets",
    name: "google-sheets",
    title: {
      en: "Google Sheets",
      zh: "Google Sheets",
    },
    description: {
      en: "Read and update spreadsheets.",
      zh: "读取和更新电子表格。",
    },
    url: "https://sheetsmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/spreadsheets.readonly",
      "https://www.googleapis.com/auth/spreadsheets",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/sheets/",
    iconUrl: MCP_CATALOG_ICON_URLS["google-sheets.svg"],
    order: 40,
  },
  {
    id: "google-slides",
    name: "google-slides",
    title: {
      en: "Google Slides",
      zh: "Google Slides",
    },
    description: {
      en: "Read and edit presentations.",
      zh: "读取和编辑演示文稿。",
    },
    url: "https://slidesmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/drive.readonly",
      "https://www.googleapis.com/auth/drive.file",
      "https://www.googleapis.com/auth/presentations.readonly",
      "https://www.googleapis.com/auth/presentations",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/slides/",
    iconUrl: MCP_CATALOG_ICON_URLS["google-slides.svg"],
    order: 50,
  },
  {
    id: "google-calendar",
    name: "google-calendar",
    title: {
      en: "Google Calendar",
      zh: "Google Calendar",
    },
    description: {
      en: "View and manage events and calendars.",
      zh: "查看和管理日程与日历。",
    },
    url: "https://calendarmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/calendar.calendarlist.readonly",
      "https://www.googleapis.com/auth/calendar.events.freebusy",
      "https://www.googleapis.com/auth/calendar.events.readonly",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/calendar/",
    iconUrl: MCP_CATALOG_ICON_URLS["google-calendar.svg"],
    order: 60,
  },
  {
    id: "google-chat",
    name: "google-chat",
    title: {
      en: "Google Chat",
      zh: "Google Chat",
    },
    description: {
      en: "Search conversations and send messages.",
      zh: "搜索会话并发送消息。",
    },
    url: "https://chatmcp.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/chat.spaces.readonly",
      "https://www.googleapis.com/auth/chat.memberships.readonly",
      "https://www.googleapis.com/auth/chat.messages.readonly",
      "https://www.googleapis.com/auth/chat.messages.create",
      "https://www.googleapis.com/auth/chat.users.readstate",
    ],
    category: "google-workspace",
    website: "https://workspace.google.com/products/chat/",
    iconUrl: MCP_CATALOG_ICON_URLS["google-chat.svg"],
    order: 70,
  },
  {
    id: "google-people",
    name: "google-people",
    title: {
      en: "People",
      zh: "People",
    },
    description: {
      en: "Look up profiles, contacts, and directory people.",
      zh: "查询个人资料、联系人和目录成员。",
    },
    url: "https://people.googleapis.com/mcp/v1",
    defaultAuthKind: "oauth",
    oauthScopes: [
      "https://www.googleapis.com/auth/directory.readonly",
      "https://www.googleapis.com/auth/userinfo.profile",
      "https://www.googleapis.com/auth/contacts.readonly",
    ],
    category: "google-workspace",
    website: "https://developers.google.com/people",
    iconUrl: MCP_CATALOG_ICON_URLS["google-people.svg"],
    order: 80,
  },
  {
    id: "microsoft-365",
    name: "microsoft-365",
    title: {
      en: "Microsoft 365",
      zh: "Microsoft 365",
    },
    description: {
      en: "Microsoft 365 roadmap, Azure updates, and release communications.",
      zh: "Microsoft 365 路线图、Azure 更新与发布信息。",
    },
    url: "https://www.microsoft.com/releasecommunications/mcp",
    defaultAuthKind: "none",
    category: "productivity",
    website: "https://www.microsoft.com",
    iconUrl: MCP_CATALOG_ICON_URLS["microsoft-365.svg"],
    order: 10,
  },
  {
    id: "asana",
    name: "asana",
    title: {
      en: "Asana",
      zh: "Asana",
    },
    description: {
      en: "Tasks, projects, and workspaces.",
      zh: "任务、项目与工作区。",
    },
    url: "https://mcp.asana.com/v2/mcp",
    defaultAuthKind: "oauth",
    category: "productivity",
    website: "https://asana.com",
    iconUrl: MCP_CATALOG_ICON_URLS["asana.svg"],
    order: 20,
  },
  {
    id: "monday",
    name: "monday",
    title: {
      en: "monday.com",
      zh: "monday.com",
    },
    description: {
      en: "Work management, boards, and automations.",
      zh: "工作管理、看板与自动化。",
    },
    url: "https://mcp.monday.com/mcp",
    defaultAuthKind: "oauth",
    category: "productivity",
    website: "https://monday.com",
    iconUrl: MCP_CATALOG_ICON_URLS["monday.svg"],
    order: 30,
  },
  {
    id: "hubspot",
    name: "hubspot",
    title: {
      en: "HubSpot",
      zh: "HubSpot",
    },
    description: {
      en: "CRM, marketing, and customer data.",
      zh: "CRM、营销与客户数据。",
    },
    url: "https://mcp.hubspot.com",
    defaultAuthKind: "oauth",
    category: "productivity",
    website: "https://www.hubspot.com",
    iconUrl: MCP_CATALOG_ICON_URLS["hubspot.svg"],
    order: 40,
  },
  {
    id: "figma",
    name: "figma",
    title: {
      en: "Figma",
      zh: "Figma",
    },
    description: {
      en: "Files, designs, and Dev Mode context.",
      zh: "文件、设计与开发模式上下文。",
    },
    url: "https://mcp.figma.com/mcp",
    defaultAuthKind: "oauth",
    category: "design",
    website: "https://www.figma.com",
    iconUrl: MCP_CATALOG_ICON_URLS["figma.svg"],
    order: 10,
  },
  {
    id: "canva",
    name: "canva",
    title: {
      en: "Canva",
      zh: "Canva",
    },
    description: {
      en: "Designs, assets, and exports.",
      zh: "设计、素材与导出。",
    },
    url: "https://mcp.canva.com/mcp",
    defaultAuthKind: "oauth",
    category: "design",
    website: "https://www.canva.com",
    iconUrl: MCP_CATALOG_ICON_URLS["canva.svg"],
    order: 20,
  },
  {
    id: "tavily",
    name: "tavily",
    title: {
      en: "Tavily",
      zh: "Tavily",
    },
    description: {
      en: "Web search and research.",
      zh: "网页搜索与研究。",
    },
    url: "https://mcp.tavily.com/mcp",
    defaultAuthKind: "none",
    category: "search",
    website: "https://tavily.com",
    iconUrl: MCP_CATALOG_ICON_URLS["tavily.svg"],
    order: 10,
  },
  {
    id: "firecrawl",
    name: "firecrawl",
    title: {
      en: "Firecrawl",
      zh: "Firecrawl",
    },
    description: {
      en: "Web scraping, crawling, and extraction.",
      zh: "网页抓取、爬取与提取。",
    },
    url: "https://mcp.firecrawl.dev/v2/mcp",
    defaultAuthKind: "none",
    category: "search",
    website: "https://www.firecrawl.dev",
    iconUrl: MCP_CATALOG_ICON_URLS["firecrawl.svg"],
    order: 20,
  },
  {
    id: "zapier",
    name: "zapier",
    title: {
      en: "Zapier",
      zh: "Zapier",
    },
    description: {
      en: "Connect to 9,000+ apps and workflows.",
      zh: "连接 9,000+ 应用与自动化流程。",
    },
    url: "https://mcp.zapier.com/api/v1/connect",
    defaultAuthKind: "oauth",
    category: "automation",
    website: "https://zapier.com",
    iconUrl: MCP_CATALOG_ICON_URLS["zapier.svg"],
    order: 10,
  },
  {
    id: "airtable",
    name: "airtable",
    title: {
      en: "Airtable",
      zh: "Airtable",
    },
    description: {
      en: "Bases, tables, records, and business workflows.",
      zh: "数据库、数据表、记录与业务流程。",
    },
    url: "https://mcp.airtable.com/mcp",
    defaultAuthKind: "oauth",
    category: "business-data",
    website: "https://www.airtable.com",
    iconUrl: MCP_CATALOG_ICON_URLS["airtable.svg"],
    order: 10,
  },
  {
    id: "supabase",
    name: "supabase",
    title: {
      en: "Supabase",
      zh: "Supabase",
    },
    description: {
      en: "Projects, databases, and backend development.",
      zh: "项目、数据库与后端开发。",
    },
    url: "https://mcp.supabase.com/mcp",
    defaultAuthKind: "oauth",
    category: "business-data",
    website: "https://supabase.com",
    iconUrl: MCP_CATALOG_ICON_URLS["supabase.svg"],
    order: 20,
  },
  {
    id: "amplitude",
    name: "amplitude",
    title: {
      en: "Amplitude",
      zh: "Amplitude",
    },
    description: {
      en: "Product analytics, funnels, and retention.",
      zh: "产品分析、漏斗与留存。",
    },
    url: "https://mcp.amplitude.com/mcp",
    defaultAuthKind: "oauth",
    category: "business-data",
    website: "https://amplitude.com",
    iconUrl: MCP_CATALOG_ICON_URLS["amplitude.svg"],
    order: 30,
  },
  {
    id: "stripe",
    name: "stripe",
    title: {
      en: "Stripe",
      zh: "Stripe",
    },
    description: {
      en: "Payments, customers, and subscriptions.",
      zh: "支付、客户与订阅。",
    },
    url: "https://mcp.stripe.com",
    defaultAuthKind: "oauth",
    category: "business-data",
    website: "https://stripe.com",
    iconUrl: MCP_CATALOG_ICON_URLS["stripe.svg"],
    order: 40,
  },
];
