/**
 * Generated by scripts/generate-mcp-catalog.mjs from mcp-categories.yaml, mcp-catalog.yaml, and icons/*.
 * Do not edit by hand. Run `pnpm catalog:generate`.
 */
import type { MCPAuthKind } from "@opentag/shared/browser";

/** The locales the Web App supports, taken from its i18n project settings. */
export type McpCatalogLocale = "en" | "zh";

/** Card and tab copy. Every supported locale is required, so a card never falls back silently. */
export type McpCatalogLocalizedText = Record<McpCatalogLocale, string>;

/** The card marks, embedded as data URLs: one declaration per distinct icon file. */
export const MCP_CATALOG_ICON_URLS = {
  "exa.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5FPC90ZXh0Pjwvc3ZnPgo=",
  "linear.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5MPC90ZXh0Pjwvc3ZnPgo=",
  "notion.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5OPC90ZXh0Pjwvc3ZnPgo=",
  "sentry.svg":
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgYXJpYS1oaWRkZW49InRydWUiPjxyZWN0IHg9IjIuNzUiIHk9IjIuNzUiIHdpZHRoPSIxOC41IiBoZWlnaHQ9IjE4LjUiIHJ4PSI1IiBmaWxsPSJub25lIiBzdHJva2U9ImN1cnJlbnRDb2xvciIgc3Ryb2tlLXdpZHRoPSIxLjUiLz48dGV4dCB4PSIxMiIgeT0iMTYuMiIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZm9udC1mYW1pbHk9Ik1hbnJvcGUsIHN5c3RlbS11aSwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMSIgZm9udC13ZWlnaHQ9IjcwMCIgZmlsbD0iY3VycmVudENvbG9yIj5TPC90ZXh0Pjwvc3ZnPgo=",
} as const;

export type McpCatalogCategory = {
  id: string;
  label: McpCatalogLocalizedText;
  order: number;
};

export type McpCatalogEntry = {
  id: string;
  name: string;
  title: McpCatalogLocalizedText;
  description: McpCatalogLocalizedText;
  url: string;
  defaultAuthKind: MCPAuthKind;
  authHeader?: string;
  authScheme?: string;
  extraHeaders?: Record<string, string>;
  category: string;
  website: string;
  iconUrl: string;
  order: number;
};

/** Tab order is this array's order. */
export const MCP_CATALOG_CATEGORIES: readonly McpCatalogCategory[] = [
  {
    id: "general",
    label: {
      en: "General",
      zh: "通用",
    },
    order: 10,
  },
  {
    id: "engineering",
    label: {
      en: "Engineering",
      zh: "工程",
    },
    order: 20,
  },
];

/** Grouped by category order, then entry order. */
export const MCP_CATALOG_ENTRIES: readonly McpCatalogEntry[] = [
  {
    id: "notion",
    name: "notion",
    title: {
      en: "Notion",
      zh: "Notion",
    },
    description: {
      en: "Docs, wikis, and project pages.",
      zh: "文档、知识库与项目页面。",
    },
    url: "https://mcp.notion.com/mcp",
    defaultAuthKind: "oauth",
    category: "general",
    website: "https://www.notion.com",
    iconUrl: MCP_CATALOG_ICON_URLS["notion.svg"],
    order: 10,
  },
  {
    id: "exa",
    name: "exa",
    title: {
      en: "Exa",
      zh: "Exa",
    },
    description: {
      en: "Web search and research.",
      zh: "网页搜索与研究。",
    },
    url: "https://mcp.exa.ai/mcp",
    defaultAuthKind: "none",
    category: "general",
    website: "https://exa.ai",
    iconUrl: MCP_CATALOG_ICON_URLS["exa.svg"],
    order: 20,
  },
  {
    id: "linear",
    name: "linear",
    title: {
      en: "Linear",
      zh: "Linear",
    },
    description: {
      en: "Issues, projects, and cycles.",
      zh: "事务、项目与迭代。",
    },
    url: "https://mcp.linear.app/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://linear.app",
    iconUrl: MCP_CATALOG_ICON_URLS["linear.svg"],
    order: 10,
  },
  {
    id: "sentry",
    name: "sentry",
    title: {
      en: "Sentry",
      zh: "Sentry",
    },
    description: {
      en: "Errors, traces, and releases.",
      zh: "错误、链路追踪与发布。",
    },
    url: "https://mcp.sentry.dev/mcp",
    defaultAuthKind: "oauth",
    category: "engineering",
    website: "https://sentry.io",
    iconUrl: MCP_CATALOG_ICON_URLS["sentry.svg"],
    order: 20,
  },
];
